name: CI/Release

on:
  push:
    branches: ["main", "master"]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  ci-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v2
        with:
          install: true

      - name: Install dependencies
        run: mise run install

      - name: Codegen
        run: mise run codegen

      - name: Create PR or Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: update data"

            BRANCH_NAME="update-data-$(date +%s)"
            git checkout -b "$BRANCH_NAME"
            git push origin "$BRANCH_NAME"

            gh pr create \
              --title "chore: update data" \
              --body "Automated data update." \
              --base "main" \
              --head "$BRANCH_NAME" || echo "⚠️ Failed to create PR. This might be due to repository settings. Changes are pushed to branch $BRANCH_NAME."
          else
            echo "No changes to commit."
          fi

      - name: CI
        run: mise run ci

      - name: Prepare Artifacts
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        run: zip -r data.zip bruto

      - name: Release
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            TAG_NAME="release-$(date +%Y%m%d%H%M%S)"
          fi
          gh release create "$TAG_NAME" data.zip --generate-notes

      - name: Upload Artifacts to Workflow
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: data.zip
